image:
  repository: devops-proj-application
  tag: 35cd872
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

serviceAccount:
  enabled: false

autoScaling:
  enabled: false 