image:
  repository: arpitamisal/devops-proj
  tag: 2bc7606
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

serviceAccount:
  enabled: false

autoscaling:
  enabled: false 

httpRoute:
  enabled: false

replicaCount: 1